language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

before_install:
  - wget http://get.sensiolabs.org/php-cs-fixer.phar

before_script:
  - composer self-update
  - composer install --dev
  - mkdir -p build/cov
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/cov/clover.xml
  - output=$(php php-cs-fixer.phar fix -v --dry-run .); if [[ $output ]]; then while read -r line; do echo -e "$line"; done <<< "$output"; false; fi;

after_script:
  - ./vendor/bin/coveralls -v
  - CODECLIMATE_REPO_TOKEN=8c4056b715faa506631045ecbc23b1d92f8a04ab8d9ee39b43110afeaa232328 ./vendor/bin/test-reporter --coverage-report=build/cov/clover.xml
